root: true
parser: '@typescript-eslint/parser'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:unicorn/recommended'
plugins:
    - '@typescript-eslint'
rules:
    unicorn/no-static-only-class: 'off'
